// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Energy_monitor

#include "backlight.h"
#include "main.h"
#include "ui.h"

extern Backlight backlight;

void ui_toggleBacklight(lv_event_t* e) {
  backlight.toggleBacklightManually();
}
