// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Energy_monitor

#ifndef _ENERGY_MONITOR_UI_H
#define _ENERGY_MONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
extern lv_obj_t *ui_LoadingScreen;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_LoadingLabel;
extern lv_obj_t *ui_Spinner2;
// SCREEN: ui_OKScreen
void ui_OKScreen_screen_init(void);
extern lv_obj_t *ui_OKScreen;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_LabelRezervaOK;
extern lv_obj_t *ui_ArcCurrentWatts;
extern lv_obj_t *ui_Label5;
// SCREEN: ui_ErrorScreen
void ui_ErrorScreen_screen_init(void);
extern lv_obj_t *ui_ErrorScreen;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_LabelRezervaError;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_PanelAppliance;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_Calibri32);
LV_FONT_DECLARE( ui_font_Calibri16);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
