// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Energy_monitor

#ifndef UI_LOADINGSCREEN_H
#define UI_LOADINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LoadingScreen
extern void ui_LoadingScreen_screen_init(void);
extern void ui_LoadingScreen_screen_destroy(void);
extern lv_obj_t * ui_LoadingScreen;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_LoadingLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

