// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Energy_monitor

#ifndef UI_OKSCREEN_H
#define UI_OKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OKScreen
extern void ui_OKScreen_screen_init(void);
extern void ui_OKScreen_screen_destroy(void);
extern void ui_event_OKScreen(lv_event_t * e);
extern lv_obj_t * ui_OKScreen;
extern lv_obj_t * ui_PanelTopOK;
extern lv_obj_t * ui_LabelRemainingWattsOK;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ArcWorstCaseWattsOK;
extern lv_obj_t * ui_ArcCurrentWattsOK;
extern lv_obj_t * ui_LabelWattsUsedOK;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

