// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Energy_monitor

#include "../ui.h"

void ui_LoadingScreen_screen_init(void)
{
ui_LoadingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LoadingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_LoadingScreen, &ui_font_Calibri16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_LoadingScreen);
lv_obj_set_width( ui_Panel2, 400);
lv_obj_set_height( ui_Panel2, 102);
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoadingLabel = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_LoadingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoadingLabel, 2 );
lv_obj_set_y( ui_LoadingLabel, 2 );
lv_obj_set_align( ui_LoadingLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LoadingLabel,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_LoadingLabel,"Starting");
lv_obj_set_style_text_font(ui_LoadingLabel, &ui_font_Calibri32, LV_PART_MAIN| LV_STATE_DEFAULT);

}
